tags:
  - name: Auth
    description: Authentication-related endpoints

paths:
  /auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Request password reset
      description: Sends a password reset link to the user's email if the email exists in the system.
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: soorajydv9@gmail.com
      responses:
        '200':
          description: Password reset email sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password reset email sent
        '400':
          description: Email missing or not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    oneOf:
                      - example: Email is required
                      - example: Email not found
