tags:
  - name: Auth
    description: Endpoints related to user authentication and registration

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: User login
      description: Authenticates a user and provides an access token and refresh token.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user attempting to log in.
                  example: "soorajydv9@gmail.com"
                password:
                  type: string
                  description: The password of the user.
                  example: "Password@123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Login successful"
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          _id:
                            type: string
                            example: "681c91f724f3b01481623d6a"
                          name:
                            type: string
                            example: "soorajydv"
                          email:
                            type: string
                            example: "soorajydv9@gmail.com"
                          role:
                            type: string
                            example: "user"
                          isActive:
                            type: boolean
                            example: true
                          isVerified:
                            type: boolean
                            example: true
                          isOauth:
                            type: boolean
                            example: false
                      accessToken:
                        type: string
                        description: "JWT access token for authentication"
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      refreshToken:
                        type: string
                        description: "JWT refresh token to obtain new access tokens"
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Invalid login credentials or unverified user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: ["Invalid password","User is not verified, please verify your email first"]
