tags:
  - name: Auth
    description: Endpoints related to user authentication and registration

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      description: Creates a new user account with a name, email, password, and role.
      operationId: signupUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - role
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 50
                  pattern: "^[a-zA-Z\\s]+$"
                  description: Full name of the user
                  example: "Sooraj Yadav"
                email:
                  type: string
                  format: email
                  description: User email address
                  example: "soorajydv9@gmail.com"
                password:
                  type: string
                  minLength: 8
                  description: >
                    Password must contain at least one uppercase letter, one lowercase letter,
                    one number, and one special character.
                  example: "Passw0rd!"
                role:
                  type: string
                  enum:
                    - user
                    - admin
                  description: Role assigned to the user
                  example: "user"
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User registered successfully
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          _id:
                            type: string
                            example: "681c91f724f3b01481623d6a"
                          name:
                            type: string
                            example: "soorajydv"
                          email:
                            type: string
                            example: "soorajydv9@gmail.com"
                          role:
                            type: string
                            example: "user"
                          isActive:
                            type: boolean
                            example: true
                          isVerified:
                            type: boolean
                            example: false
                          isOauth:
                            type: boolean
                            example: false
                      accessToken:
                        type: string
                        example: >
                          eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '400':
          description: Invalid input or bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request data
