tags:
  - name: Auth
    description: Authentication-related endpoints

paths:
  /auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset user password
      description: Resets the user's password using a valid reset token.
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
                - confirmNewPassword
              properties:
                token:
                  type: string
                  description: Reset token from the email
                  example: 9f8c4d57c6d444b1a44cf259e2cd687899fe7e2b6c83980b7a7506b12b84a7cb
                newPassword:
                  type: string
                  minLength: 8
                  maxLength: 100
                  example: NewPassword123!
                confirmNewPassword:
                  type: string
                  minLength: 8
                  maxLength: 100
                  example: NewPassword123!
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password reset successful
        '400':
          description: Invalid token or password mismatch
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    oneOf:
                      - example: Passwords do not match
                      - example: Invalid or expired token
